
services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fastapi:
    image: fastapi-image:1.0
    build: .
    container_name: fastapi-app
    env_file:
      - .env
    ports:
      - "8000:8002"
    depends_on:
      - db
    volumes:
      - ./:/app

volumes:
  postgres_data: {}


